// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_error_boundary/test/cloud/composite_error_reporter_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_error_boundary/src/error_reporter.dart' as _i2;
import 'package:flutter_error_boundary/src/error_types.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ErrorReporter].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorReporter extends _i1.Mock implements _i2.ErrorReporter {
  MockErrorReporter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> reportError(_i4.ErrorInfo? errorInfo) => (super.noSuchMethod(
        Invocation.method(
          #reportError,
          [errorInfo],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> reportErrorWithContext(
    _i4.ErrorInfo? errorInfo,
    Map<String, dynamic>? context,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reportErrorWithContext,
          [
            errorInfo,
            context,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void setUserIdentifier(String? userId) => super.noSuchMethod(
        Invocation.method(
          #setUserIdentifier,
          [userId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setUserProperties(Map<String, dynamic>? properties) =>
      super.noSuchMethod(
        Invocation.method(
          #setUserProperties,
          [properties],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void clearUserData() => super.noSuchMethod(
        Invocation.method(
          #clearUserData,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
